/* Generated By:JJTree: Do not edit this line. QueryRoot.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Query,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.processmining.xeslite.query.syntax;

public
class QueryRoot extends SimpleNode {
  public QueryRoot(int id) {
    super(id);
  }

  public QueryRoot(QueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4cf099ef84460d1dfaa06167e4b2862d (do not edit this line) */
