/* Generated By:JavaCC: Do not edit this line. QueryParserDefaultVisitor.java Version 6.0_1 */
package org.processmining.xeslite.query.syntax;

public class QueryParserDefaultVisitor implements QueryParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(QueryRoot node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(QueryBinaryLogicalExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(QuerySimpleExpression node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(QueryAtom node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=8c827b9255b628f9c23ea7edcf7a68c8 (do not edit this line) */
