/* Generated By:JJTree: Do not edit this line. QueryBinaryLogicalExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Query,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.processmining.xeslite.query.syntax;

public
class QueryBinaryLogicalExpression extends SimpleNode {
	
  public String op;
	 
  public QueryBinaryLogicalExpression(int id) {
    super(id);
  }

  public QueryBinaryLogicalExpression(QueryParser p, int id) {
    super(p, id);
  }

  public String toString() {
	return op;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2c3526122ef3d8abdf5dc5b239239469 (do not edit this line) */
