/* Generated By:JJTree: Do not edit this line. QuerySimpleExpression.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Query,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.processmining.xeslite.query.syntax;

public
class QuerySimpleExpression extends SimpleNode {
	
	public String op;
	
  public QuerySimpleExpression(int id) {
    super(id);
  }

  public QuerySimpleExpression(QueryParser p, int id) {
    super(p, id);
  }

  public String toString() {
	    return op;
  }

  /** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c24ec4a2bc219b9a50bae143860fff54 (do not edit this line) */
