/* Generated By:JJTree: Do not edit this line. QueryTerm.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Query,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.processmining.xeslite.query.syntax;

public
class QueryTerm extends SimpleNode {
  
	public String key;
	public String val;

  public QueryTerm(int id) {
    super(id);
  }

  public QueryTerm(QueryParser p, int id) {
    super(p, id);
  }

  public String toString() {
	return key;
  }

/** Accept the visitor. **/
  public Object jjtAccept(QueryParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ca3ee24d27cf7a108988aeca766d61dc (do not edit this line) */
