/* Generated By:JavaCC: Do not edit this line. QueryParserTreeConstants.java Version 6.0_1 */
package org.processmining.xeslite.query.syntax;

public interface QueryParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTBINARYLOGICALEXPRESSION = 2;
  public int JJTSIMPLEEXPRESSION = 3;
  public int JJTATOM = 4;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "BinaryLogicalExpression",
    "SimpleExpression",
    "Atom",
  };
}
/* JavaCC - OriginalChecksum=21ccc67a67161ead5b960447cb88e7c7 (do not edit this line) */
